name: Build and Push PDF Resume

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  
          persist-credentials: false 

      - name: Install Pandoc and LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex

      - name: Convert Markdown to PDF
        run: |
          pandoc resume.md -o resume.pdf --pdf-engine=xelatex

      - name: Push PDF to pdf branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git checkout --orphan pdf
          git rm -rf .
          mv resume.pdf index.pdf

          git add index.pdf
          git commit -m "Update PDF resume"
          git push --force https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} pdf
